apiVersion: v1
kind: Service
metadata:
  name: {{ include "reposilite.fullname" . }}
  annotations:
  {{- with .Values.service.annotations  }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "reposilite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: https
      {{- if (and (contains "NodePort" .Values.service.type) (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "reposilite.selectorLabels" . | nindent 4 }}
